blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<tag_slug>/', views.post_list, name='post_list_by_tag'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
        views.post_detail, name='post_detail'),
    path('<post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, 
                                    name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models

from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                        self).get_queryset().filter(status='published')

class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,
                            on_delete=models.CASCADE,
                            related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                            choices=STATUS_CHOICES,
                            default='draft')
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title
                                                                        
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                        self.publish.month,
                        self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete=models.CASCADE,
                            related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__ (self):
        return f'Comment by {self.name} on {self.post}'


    

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={
                                                                    'placeholder': 'Name',
                                                                    'id': 'sharepost-name',
                                                                    'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
                                                        'placeholder': 'Email',
                                                        'id': 'sharepost-email',
                                                        'class': 'form-control'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={
                                                    'placeholder': 'To',
                                                    'id': 'sharepost-to',
                                                    'class': 'form-control'}))
    comments = forms.CharField(required=False,
                                widget=forms.Textarea(attrs={
                                                        'placeholder': 'Comments',
                                                        'id': 'sharepost-comments',
                                                        'class': 'form-control'}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'id': 'comment-name',
                                            'class': 'form-control',
                                            'placeholder': 'Name'}),
            'email': forms.EmailInput(attrs={'id': 'comment-email',
                                                'class': 'form-control',
                                                'placeholder': 'Email'}),
            'body': forms.Textarea(attrs={'id': 'comment-body',
                                            'class': 'form-control',
                                            'placeholder': 'Comment'})
        }


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    query = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    if 'query' in request.GET:
        if len(request.GET.get('query')) > 0:
            query = request.GET.get('query')
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            object_list = Post.published.annotate(search=search_vector,
                                                    rank=SearchRank(search_vector, search_query)
                                                    ).filter(search=search_query).order_by('-rank')


    paginator = Paginator(object_list, 2) # 3 posts in each page
    page = request.GET.get('page')
    print(page)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page Is not an Integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of ranger deliver last page of the result
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html', {'page': page,
                                                'posts': posts,
                                                'tag': tag,
                                                'searchquery': query})


"""
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 1
    template_name = 'blog/post/list.html'
"""


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similiar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')
    return render(request, 'blog/post/detail.html', {'post': post,
                                                    'comments': comments,
                                                    'new_comment': new_comment,
                                                    'comment_form': comment_form,
                                                    'similar_posts':similar_posts})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ...send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends your read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                        f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'nfsrivalsuploaded@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                        'form': form,
                                                        'sent':sent})

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <article class="post-article">
        <header>
            <h2 class="display-4"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <p class="font-weight-lighter post-info font-italic">
                Published {{ post.publish }} by {{ post.author }}
            </p>
        </header>
        <div class="container-fluid shadow-sm bg-white">
            <p>
            {{ post.body|markdown }}
            </p>
        <div>
    </article>
    <p>
        <a href="{% url 'blog:post_share' post.id %}" class="btn btn-outline-info" role="button" style="float:right;">
        Share
        </a>
    </p>

    <h4>Related Posts</h4>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <p class=text-right>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </p>
    {% endwith %}

    {% for comment in comments %}
    <div class="media p-3 comment">
        <div class="media-body">
            <h4><small>{{ comment.name }} on {{ comment.created }}</small></h4>
            <p>{{ comment.body|linebreaks }}</p>
        </div>
    </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
        {% for field in comment_form %}
            <div class="form-group">
                {{ field }}
            </div>
        {% endfor %}
        {% csrf_token %}
        <p><input class="btn btn-secondary" type="submit" value="Add comment"></p>
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul class="list-group">
    {% for post in latest_posts %}
        <li class="list-group-item">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}

{% block content %}
    {% if searchquery %}
        <h2>Posts containing "{{ searchquery }}"</h2>
        {% if not posts %}
            <p>0 posts found</p> 
        {% endif %}
    {% endif %}
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <article>
            <h2>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}"><span class="badge badge-pill badge-info">{{ tag }}</span></a>
            {% endfor %}
            <p class="font-weight-light post-info">
                Published {{ post.publish }} by {{ post.author }}
            </p>
            {{ post.body|markdown|truncatewords_html:30 }}
        </article>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post {% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }} by e-mail</h1>
        <form method="post">
        {% for field in form %}
            <div class="form-group">
                {{ field.errors }}
                {{ field }}
            </div>
        {% endfor %}
            {% csrf_token %}
            <input class="btn btn-secondary" type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}
    